### ISSUE TITLE
Traceback terminates prematurely

### ISSUE THREAD

**Issue by koirikivi** [tetframework/Tonnikala#5]
I tried to get pyramid_webpack to work and got the following error:

```TypeError: the JSON object must be str, not 'bytes'```

The last line of the traceback shown by DONT PANIC was:

```<script py:for="asset in request.webpack().get_bundle('main')" src="$asset.url"></script>```

Nevermind the actual cause of the error, it seems to me that the bottom-most line of the traceback should be the package the issue originated from, not Tonnikala.

**Comment by ztane** [comment]
This was fixed, see Tonnikala 1.0.0b4.
