### ISSUE TITLE
Weird traceback issue with parent templates

### ISSUE THREAD

**Issue by koirikivi** [tetframework/Tonnikala#6]
Got this in traceback when running `pserve --reload development.ini`:

```
<script py:for="asset in request.webpack().get_bundle('main')" src="$asset.url"></script>
AttributeError: 'dict' object has no attribute 'url'
```

Corrected the code and got this

```
<script py:for="asset in request.webpack().get_bundle('main')" src="$asset['url']"></script>
AttributeError: 'dict' object has no attribute 'url'
```

Notice `$asset['url']` instead of `$asset.url`. So the code line in the traceback is updated correctly but the previous error still survives.

Restarting `pserve` fixes the issue.

The code is in a parent template extended by a child template.

**Comment by ztane** [comment]
Fixed template reloading of child templates; released 1.0.0b4. Thanks.
